"""
Data models for syllabus topics and lesson plans
"""

from dataclasses import dataclass, field
from typing import List, Optional


@dataclass
class Topic:
    """Represents a single topic in the 200-part syllabus"""
    part: int
    title: str
    category: str  # "verbal_reasoning" or "analytical_reasoning"
    subtopics: List[str] = field(default_factory=list)
    difficulty: str = "intermediate"
    formulas: List[str] = field(default_factory=list)
    duration_target_minutes: int = 8

    @property
    def category_display(self) -> str:
        return self.category.replace("_", " ").title()


@dataclass
class FormulaBlock:
    """A formula with explanation for display"""
    formula: str
    explanation: str
    visual_label: str = ""


@dataclass
class Example:
    """A solved example with step-by-step solution"""
    question: str
    steps: List[str] = field(default_factory=list)
    answer: str = ""
    explanation: str = ""


@dataclass
class Question:
    """A practice question with options"""
    question: str
    options: List[str] = field(default_factory=list)  # ["A) ...", "B) ...", ...]
    correct_answer: str = ""
    explanation: str = ""


@dataclass
class LessonPlan:
    """Complete lesson plan generated by LLM"""
    topic: Topic
    introduction: str = ""
    concept_explanation: str = ""
    formulas: List[FormulaBlock] = field(default_factory=list)
    solved_examples: List[Example] = field(default_factory=list)
    tips_and_tricks: List[str] = field(default_factory=list)
    practice_questions: List[Question] = field(default_factory=list)
    summary_points: List[str] = field(default_factory=list)

    def get_narration_text(self) -> str:
        """Get complete narration text for TTS (Hinglish) including intro welcome and outro CTA."""
        parts = []

        # Intro welcome (spoken at the very beginning)
        parts.append(
            f"Namaste doston! Reasoning Mastery mein aapka swagat hai. "
            f"Yeh hai Part {self.topic.part} of 200. "
            f"Doston, yeh video aapke liye bahut important hai, toh please last tak zaroor dekhiye. "
            f"Maine is video ke end mein aur comment section mein kuch bahut important practice questions share kiye hain "
            f"jo aapke exam mein zaroor aayenge, toh video poora dekhiye aur comment section zaroor check kariye. "
            f"Chaliye shuru karte hain!"
        )

        # Introduction from LLM
        if self.introduction:
            parts.append(self.introduction)

        # Concept explanation
        if self.concept_explanation:
            parts.append(self.concept_explanation)

        # Formulas
        for fb in self.formulas:
            parts.append(fb.explanation)

        # Solved examples
        for i, ex in enumerate(self.solved_examples, 1):
            parts.append(ex.question)
            for step in ex.steps:
                parts.append(step)
            parts.append(ex.answer + ". " + ex.explanation if ex.explanation else ex.answer)

        # Tips and tricks
        if self.tips_and_tricks:
            for tip in self.tips_and_tricks:
                parts.append(tip)

        # Practice questions mention
        if self.practice_questions:
            parts.append(
                f"Practice question number 1. {self.practice_questions[0].question}. "
                f"Iska answer pinned comment mein check kariye."
            )

        # Summary
        if self.summary_points:
            for point in self.summary_points:
                parts.append(point)

        # Outro CTA (spoken at the very end)
        next_part = f"Part {self.topic.part + 1}" if self.topic.part < 200 else "Series Complete"
        parts.append(
            f"Toh doston, aaj ka topic yahan pe complete hota hai. "
            f"Umeed karta hoon aapko yeh video helpful lagi hogi. "
            f"Doston, maine comment section mein kuch bahut important practice questions share kiye hain "
            f"jo previous year exams mein baar baar puche gaye hain. "
            f"Please in questions ko zaroor solve kariye aur apna answer comment mein likhiye, "
            f"main aapko reply karunga ki sahi hai ya galat. "
            f"Agar yeh video aapko achhi lagi toh please like button dabayiye, "
            f"isse mujhe motivation milta hai aur aapke liye aur achhe videos banane mein madad hoti hai. "
            f"Aur agar aapne abhi tak channel subscribe nahi kiya hai toh abhi kariye "
            f"aur bell icon zaroor dabayiye taaki har nayi video ki notification aapko mil sake. "
            f"Yeh 200 parts ki complete series hai, ek bhi video mat miss kariye, "
            f"agar aapne poori series complete kar li toh exam mein reasoning section mein full marks pakke hain. "
            f"Apne doston ko bhi share kariye jinko isse fayda ho sakta hai. "
            f"Milte hain next video mein {next_part} ke saath. Tab tak practice karte rahiye! "
            f"Jai Hind!"
        )

        return " ... ".join(parts)

    def get_study_notes(self) -> str:
        """Get formatted study notes for YouTube comment"""
        lines = []
        lines.append(f"KEY CONCEPTS:")
        if self.concept_explanation:
            # Take first 2 sentences as summary
            sentences = self.concept_explanation.split(". ")[:3]
            for s in sentences:
                lines.append(f"  - {s.strip()}")

        if self.formulas:
            lines.append(f"\nIMPORTANT FORMULAS:")
            for fb in self.formulas:
                lines.append(f"  {fb.formula}")

        if self.tips_and_tricks:
            lines.append(f"\nTIPS & TRICKS:")
            for i, tip in enumerate(self.tips_and_tricks, 1):
                lines.append(f"  {i}. {tip}")

        return "\n".join(lines)

    def get_practice_text(self) -> str:
        """Get formatted practice questions for YouTube comment"""
        lines = []
        for i, q in enumerate(self.practice_questions, 1):
            lines.append(f"Q{i}. {q.question}")
            for opt in q.options:
                lines.append(f"  {opt}")
            lines.append("")
        return "\n".join(lines)

    def get_answer_key(self) -> str:
        """Get answer key for practice questions"""
        lines = []
        for i, q in enumerate(self.practice_questions, 1):
            lines.append(f"Q{i}: {q.correct_answer}")
            if q.explanation:
                lines.append(f"   Explanation: {q.explanation}")
        return "\n".join(lines)
